name: Flask CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        # Add commands to run your tests here
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: iustin05/sep6_moviedb:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'cinemate'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_e3c6cd5f236b47e6a411036e097b25b2 }}
          images: 'ghcr.io/iustin05/SEP6_movieDB:feature-init-flask-project'
